morse_dict = {'a': '*-',
              'b': '-***',
              'c': '-*-*',
              'd': '-**',
              'e': '*',
              'f': '**-*',
              'g': '--*',
              'h': '****',
              'i': '**',
              'j': '*---',
              'k': '-*-',
              'l': '*-**',
              'm': '--',
              'n': '-*',
              'o': '---',
              'p': '*--*',
              'q': '--*-',
              'r': '*-*',
              's': '***',
              't': '-',
              'u': '**-',
              'v': '***-',
              'w': '*--',
              'x': '-**-',
              'y': '-*--',
              'z': '--**',
              '1': '*----',
              '2': '**---',
              '3': '***--',
              '4': '****-',
              '5': '*****',
              '6': '-****',
              '7': '--***',
              '8': '---**',
              '9': '----*',
              '0': '-----',
              '.': '*-*-*-',
              ',': '--**--',
              ':': '---***',
              '?': '**--**',
              "'": '*----*',
              '-': '-****-',
              '/': '-**-*',
              '(': '-*--*-',
              ')': '-*--*-',
              '"': '*-**-*',
              ' ': ' '
              }
symbol_dict = {'`': 'grave accent',
               '~': 'tilde',
               '!': 'exclamation mark',
               '@': 'at sign',
               '#': 'hash',
               '$': 'dollar sign',
               '%': 'percent sign',
               '^': 'carat',
               '&': 'and',
               '*': 'asterisk',
               '-': 'hyphen',
               '_': 'underscore',
               '=': 'equal sign',
               '+': 'plus sign',
               '[': 'open bracket',
               ']': 'close bracket',
               '{': 'open brace',
               '}': 'close brace',
               '|': 'vertical pipe',
               ';': 'semicolon',
               '<': 'less than',
               '>': 'greater than',
               }

user_input = input("What's the text: ")
morse_code = ""
for c in user_input:
    morse_code += morse_dict[c]

print(morse_code)